# Generated by Django 5.1 on 2024-09-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=255)),
                ('org_email', models.EmailField(max_length=254, unique=True)),
                ('org_password', models.CharField(max_length=50)),
            ],
        ),
    ]
