# Generated by Django 5.1 on 2024-09-03 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_organization'),
        ('myapp', '0002_registers_user'),
    ]

    operations = [
    ]
