# Generated by Django 5.1 on 2024-09-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_organization_user_orgprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgprofile',
            name='organization_email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
