# Generated by Django 5.1 on 2024-09-22 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_orgprofile_organization_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrgProfile',
        ),
    ]
