# Generated by Django 5.1 on 2024-10-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_campaign_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='amount_raised',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
