# Generated by Django 5.1 on 2024-10-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_campaign_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
