# Generated by Django 5.1 on 2024-10-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_campaign_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_organization',
            field=models.BooleanField(default=False),
        ),
    ]
